name: build

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: ${{ github.event_name == 'pull_request' }}
      - run: go mod tidy
      - run: go test -v ./...
      - name: build release assets
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --rm-dist

      - name: Upload assets
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: goreleaser
          path: dist/*